### ISSUE TITLE
Is nn c++11 compatible?

### ISSUE THREAD

**Issue by webmaster128** [dropbox/nn#6]
When reading the nn code, we found  generic lambdas in NN_CHECK_ASSERT and NN_CHECK_THROW, which require c++14, right?

Now those are called "sample implementations" in the comment at the top, so those might be kind of optional.

Is it possible to make the core of nn a C++11 project?

**Comment by artwyman** [comment]
A quick test suggests that C++11 works fine.  I was able to make the tests compile and run with `-std=c++11` by simply replacing `auto` in those macros with `typename std::remove_reference<decltype(_e)>::type`.  I think that might be just as efficient, though I haven't thought though all the possible types of references and how they'd be handled by copy vs. move.  It might need some more metaprogramming magic to optimize every case.

@j4cbo should probably chime on whether to accept such a change, but in the mean time you can certainly make your own versions of those macros and use the nn<> template as-is.  Those macros are marked as "samples" because we assume you might have your own preferences around asserts and logging.  We certainly have our own custom versions at Dropbox for that reason.

**Comment by j4cbo** [comment]
I think @artwyman's suggestion is the right way to do it - the parameter is supposed to be by value so it can be moved/copied at the call site and then moved back out again. Small changes like this that improve backwards-compatibility without much cost seem like a good idea to me.

**Comment by webmaster128** [comment]
Thanks for the feedback. If you want, I can try to integrate this in our c++11 project and provide feedback for the proposed solution before changing it for all users.

**Comment by j4cbo** [comment]
That would be great. Thanks!

**Comment by aggsol** [comment]
Any news here?

**Comment by webmaster128** [comment]
I scheduled testing the proposed solution for beginning of June

**Comment by webmaster128** [comment]
With @artwyman's [suggestion](https://github.com/dropbox/nn/issues/6#issuecomment-280549597) integrated, nn works fine in a medium-sized C++11 project (MSVS 2015, clang 3.6, clang 3.7).

**Comment by artwyman** [comment]
Cool, @webmaster128, want to send a pull request?
